---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/scores":
    get:
      summary: list scores
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Score"
  "/api/scores/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show score
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Score"
        '404':
          description: not found
components:
  schemas:
    Score:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        key:
          type: integer
        key_name:
          type: string
        tempo:
          type: integer
          nullable: true
        time_signature:
          type: string
          nullable: true
      required:
      - id
      - title
      - key
      - key_name
      - tempo
      - time_signature
servers:
- url: http://localhost:3000
